# Generated by Django 3.2 on 2022-11-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_product_seller'),
        ('orders', '0002_auto_20221116_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='catalogue.product'),
        ),
    ]
