# Generated by Django 3.2.16 on 2022-11-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
