# Generated by Django 3.2 on 2022-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
