# Generated by Django 3.1.7 on 2022-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoptions',
            options={'verbose_name': '运输选项', 'verbose_name_plural': '运输选项'},
        ),
        migrations.AlterModelOptions(
            name='paymentselections',
            options={'verbose_name': '支付选项', 'verbose_name_plural': '支付选项'},
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentselections',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
