# Generated by Django 3.2 on 2022-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221127_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AddField(
            model_name='customer',
            name='resume',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
