# Generated by Django 3.2 on 2022-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brief',
            field=models.CharField(max_length=1000, null=True, verbose_name='Category Brief'),
        ),
    ]
