# Generated by Django 3.2 on 2022-11-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationValue',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
