# Generated by Django 3.2.16 on 2022-11-22 00:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20221119_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '商品的图片', 'verbose_name_plural': '商品的图片'},
        ),
        migrations.AlterField(
            model_name='category',
            name='brief',
            field=models.CharField(max_length=1000, null=True, verbose_name='类别简介'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='类别名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='在网页中定位到商品的唯一英文字符', max_length=255, unique=True, verbose_name='安全URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogue.category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='添加商品描述（不是必须的）', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': '价格必须在 0 和 999.99 之间'}}, help_text='最高 999.99 元', max_digits=5, verbose_name='打折价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='商品是否可见：'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, error_messages={'name': {'max_length': '数量必须在 0 和 9999 之间'}}, help_text='最多9999个', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': '价格必须在 0 和 999.99 之间'}}, help_text='最高 999.99 元', max_digits=5, verbose_name='平时价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='在网页中定位到商品的唯一英文字符', max_length=255, unique=True, verbose_name='安全URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='请添加图片的描述信息', max_length=255, null=True, verbose_name='描述信息'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_feature',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
