# Generated by Django 3.2.16 on 2022-11-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20221122_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'slug重复'}, help_text='在网页中定位到商品的唯一英文字符', max_length=255, unique=True, verbose_name='安全URL'),
        ),
    ]
